name: 'Job do projeto final PGATS-PAT'

on:
  workflow_dispatch:

jobs:
  unidade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Baixando o node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      
      - name: Instalando dependências
        run: npm install
      
      - name: Instalando o mocha
        run: npm install -D mocha
      
      - name: Rodando os testes
        run: npx mocha .\teste\trabalho-final.js
  
  deploy:
    runs-on: ubuntu-latest
    needs: [unidade]

    steps:
      - name: Simulando o deploy após a execução
        run: echo "Deploy com sucesso"